apiVersion: v1
kind: ConfigMap
metadata:
  name: f5gc-pcf-config
data:
  pcfcfg.conf: |
    info:
      version: 1.0.0
      description: PCF initial local configuration
    
    configuration:
      pcfName: PCF
      sbi:
        scheme: {{ .Values.configuration.sbi.scheme }}
        registerIPv4: {{ .Values.configuration.sbi.registerIPv4 }}     # Can also be a kubernetes service IP or domain name.
        bindingIPv4: 0.0.0.0      # Can also be an ENV.
        port: {{ .Values.service.port }}
      timeFormat: 2019-01-02 15:04:05
      defaultBdtRefId: BdtPolicyId-
      nrfUri: {{ .Values.configuration.nrfUri }}
      serviceList:
        - serviceName: npcf-am-policy-control
        - serviceName: npcf-smpolicycontrol
          suppFeat: 3fff
        - serviceName: npcf-bdtpolicycontrol
        - serviceName: npcf-policyauthorization
          suppFeat: 3
        - serviceName: npcf-eventexposure
        - serviceName: npcf-ue-policy-control
      mongodb:
        name: f5gc-mongodb
        url: {{ .Values.configuration.mongodb.url }}/free5gc

  free5GC.conf: |
    db_uri: {{ .Values.configuration.mongodb.url }}/free5gc

    #all logging levels
    #panic
    #fatal
    #error
    #warn
    #debug
    #debug
    #trace
    logger:
    # network function
      AMF:
        debugLevel: debug
        ReportCaller: true
      SMF:
        debugLevel: debug
        ReportCaller: true
      UDR:
        debugLevel: debug
        ReportCaller: true
      UDM:
        debugLevel: debug
        ReportCaller: true
      NRF:
        debugLevel: debug
        ReportCaller: true
      PCF:
        debugLevel: debug
        ReportCaller: true
      AUSF:
        debugLevel: debug
        ReportCaller: true
      N3IWF:
        debugLevel: debug
        ReportCaller: true
    # library
      NAS:
        debugLevel: debug
        ReportCaller: true
      FSM:
        debugLevel: debug
        ReportCaller: true
      NGAP:
        debugLevel: debug
        ReportCaller: true
      NamfComm:
        debugLevel: debug
        ReportCaller: true
      NamfEventExposure:
        debugLevel: debug
        ReportCaller: true
      NsmfPDUSession:
        debugLevel: debug
        ReportCaller: true
      NudrDataRepository:
        debugLevel: debug
        ReportCaller: true
      OpenApi:
        debugLevel: debug
        ReportCaller: true
      Aper:
        debugLevel: debug
        ReportCaller: true
      CommonConsumerTest:
        debugLevel: debug
        ReportCaller: true
    # webui
      WEBUI:
        debugLevel: debug
        ReportCaller: true
---        
apiVersion: v1
kind: Secret
metadata:
    name: f5gc-pcf-tls-secret
type: Opaque
data:
    {{ tpl (.Files.Glob "resources/config/cert/pcf.pem").AsSecrets . | indent 2 }}
    {{ tpl (.Files.Glob "resources/config/cert/pcf.key").AsSecrets . | indent 2 }}
