# permissions for end users to edit mobilesubscribers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mobilesubscriber-editor-role
rules:
- apiGroups:
  - slice.slice.free5gc.io
  resources:
  - mobilesubscribers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slice.slice.free5gc.io
  resources:
  - mobilesubscribers/status
  verbs:
  - get
