# permissions for end users to view mobilesubscribers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mobilesubscriber-viewer-role
rules:
- apiGroups:
  - slice.slice.free5gc.io
  resources:
  - mobilesubscribers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - slice.slice.free5gc.io
  resources:
  - mobilesubscribers/status
  verbs:
  - get
