
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - slice.slice.free5gc.io
  resources:
  - mobilesubscribers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - slice.slice.free5gc.io
  resources:
  - mobilesubscribers/finalizers
  verbs:
  - update
- apiGroups:
  - slice.slice.free5gc.io
  resources:
  - mobilesubscribers/status
  verbs:
  - get
  - patch
  - update
