apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cnf-root-{{ .Release.Name }}-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cnf-root-{{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "sdwan"
  duration: 17520h
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: cnf-root-{{ .Release.Name }}-issuer
  secretName: cnf-root-{{ .Release.Name }}-cert

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cnf-{{ .Release.Namespace }}-issuer
  namespace: {{ .Release.Namespace }}
spec:
  ca: 
    secretName: cnf-root-{{ .Release.Name }}-cert

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cnf-{{ .Release.Namespace }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: "*.{{ .Release.Namespace }}.pod.cluster.local"
  duration: 17520h
  isCA: false
  issuerRef:
    kind: Issuer
    name: cnf-{{ .Release.Namespace }}-issuer
  secretName: cnf-{{ .Release.Namespace }}-cert
  dnsNames:
  - "*.{{ .Release.Namespace }}.pod.cluster.local"
