apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-webui
  labels:
    app: f5gc-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-webui
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: f5gc-webui
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      nodeSelector:
{{ .Values.nodeSelector | toYaml | indent 8 }}
      containers:
        - name: free5g-305-webui 
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./webui"]
          resources:
{{ .Values.resources | toYaml | indent 12 }}         
          securityContext:
            privileged: false
          volumeMounts:
            - name: f5gc-webui-config
              mountPath: /free5gc/config
          ports:
            - containerPort: 5000
              name: f5gc-webui
              protocol: TCP
{{- if .Values.tcpdump.image }}
        - name: tcpdump
          image: {{ .Values.tcpdump.image }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sleep
            - infinity
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
{{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: f5gc-webui-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: f5gc-webui-config
          configMap:
            name: f5gc-webui-config
