apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-nginx-rtmp.fullname" . }}
data:
  nginx.conf.template: |
    worker_processes  auto;
    daemon off;
    worker_rlimit_nofile 8192;
    events {
      worker_connections  10240;
    }
    rtmp {
      server {
        listen 1935;
        chunk_size 4000;

        application vod {
            play /var/www/vod;
        }

        #application hls {
        #    live on;
        #    hls on;
        #    hls_nested on;
        #    hls_path /var/www/video/hls;
        #    hls_fragment 3;
        #    hls_playlist_length 60;
        #    hls_variant _low BANDWIDTH=2048000 RESOLUTION=854x480;
        #    hls_variant _mid BANDWIDTH=4096000 RESOLUTION=1280x720;
        #    hls_variant _hi  BANDWIDTH=8192000 RESOLUTION=1920x1080;
        #}
      }
    }
    http {
      server_tokens off;
      include mime.types;
      default_type application/octet-stream;
      directio 512;
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      aio on;
      #proxy_cache_path /var/www/cache levels=1:2 keys_zone=one:10m use_temp_path=off;
      server {
          listen       80;
          server_name  _;
          location / {
            root   /var/www/data; #Change this line
            sendfile on;
            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Expose-Headers' 'Content-Length';
            add_header 'X-Frame-Options' 'deny' always;

          }
          #location /hls {
          #  root /var/www/video;
          #  add_header Cache-Control no-cache;
          #  add_header 'Access-Control-Allow-Origin' '*' always;
          #  add_header 'Access-Control-Expose-Headers' 'Content-Length';
          #  types {
          #      application/vnd.apple.mpegurl m3u8;
          #      video/mp2t ts;
          #  }
          #}
      }
    }

