apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-nginx-rtmp.fullname" . }}
  labels:
    {{- include "demo-nginx-rtmp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 1935
      targetPort: 1935
      protocol: TCP
      name: rtmp
  selector:
    {{- include "demo-nginx-rtmp.selectorLabels" . | nindent 4 }}

