HelmSrc: /home/kube/emco/f5gc_deploy/networkslice/emco
f5gcHelmProf: /home/kube/emco/f5gc_deploy/networkslice/emco/free5gc/profile
ProjectName: monitor
ClusterProvider: provider2
CompositeAppMonitor: montorCompositeApp
AppMonitor: monitor
HelmAppMonitor: monitor.tar.gz
CompositeMonProfile: monitorProfile
DefaultProfileFw: f5gc-default-pr.tgz
DeploymentMonIntent: moniotrDeploymentIntent
Cluster1: clusterB
Cluster2: clusterC
Cluster1Label: edge-clusterB
Cluster2Label: edge-clusterC
ClusterMonLabel: edge-emco
Cluster1Ref: clusterB-ref
Cluster2Ref: clusterC-ref
Kube1Config: /opt/emco/kube2config
Kube2Config: /opt/emco/kube4config
AdminCloud: admin
GenericPlacementIntent: monitorGapPlacement
RsyncPort: 30441
GacPort: 30493
OvnPort: 30473
DtcPort: 30483
NpsPort: 30485
HostIP: 192.168.10.51

