
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-slice-slice-free5gc-io-v1alpha1-mobilesubscriber
  failurePolicy: Fail
  name: mmobilesubscriber.kb.io
  rules:
  - apiGroups:
    - slice.slice.free5gc.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mobilesubscribers
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-slice-slice-free5gc-io-v1alpha1-mobilesubscriber
  failurePolicy: Fail
  name: vmobilesubscriber.kb.io
  rules:
  - apiGroups:
    - slice.slice.free5gc.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - mobilesubscribers
  sideEffects: None
