# Default values for amf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

pfcp:
  #addr: free5g-smf-f5gc-smf-0.f5gc-smf.default.svc.cluster.local
  addr: f5gc-smf.free5g.prioslice.svc.cluster.local

sNssaiInfos:
  sNssai:
    sst: 2
    sd: "010203"
    dnnInfos:
      dnn: internet
      ueSubnet: 172.16.2.0/24

userplane_information:
  up_nodes:
    gNB1:
      type: AN
      an_ip: 172.16.34.2
    UPF:
      type: UPF
      #node_id: free5g-upf-f5gc-upf-0.f5gc-upf.default.svc.cluster.local
      node_id: f5gc-upf.free5g.prioslice.svc.cluster.local
      sNssaiUpfInfos:
        - sNssai:
            sst: 2
            sd: "010203"
          dnnUpfInfoList:
            - dnn: internet
        - sNssai:
            sst: 2
            sd: 10203
          dnnUpfInfoList:
            - dnn: internet
      interfaces:
        - interfaceType: N3
          endpoints:
            - 172.16.34.4
          networkInstance: internet
  links:
    - A: gNB1
      B: UPF

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name:

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 32502
  nodePort: 32502

configuration:
  sbi:
    scheme: http
    registerIPv4: f5gc-smf
  nrfUri: http://f5gc-nrf:32511

mongodb:
  url: mongodb://f5gc-mongodb.default:27017


ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
