apiVersion: v1
kind: Service
metadata:
  labels:
    app: f5gc-udr
  name: f5gc-udr
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: f5gc-udr
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
{{- end }}
  selector:
    app: f5gc-udr
