{{- if eq (.Values.git.enabled) true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-git-monitor
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.git.username | b64enc | quote }}
  token: {{ .Values.git.token | b64enc | quote }}
  repo: {{ .Values.git.repo | b64enc | quote }}
  clustername: {{ .Values.git.clustername | b64enc | quote }}
{{- end }}
