apiVersion: apps/v1
kind: Deployment
metadata:
  name: f5gc-udm
  labels:
    app: f5gc-udm
  annotations:
    free5gc.org/nssi-id: '27394d25-dbf5-428e-8fc3-f5b2add67115'
    free5gc.org/nsi-ids: '[
        { "id": "4e6db941-47d6-4fce-9c71-f7eb35a75d03" },
    ]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f5gc-udm
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: f5gc-udm
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      nodeSelector:
{{ .Values.nodeSelector | toYaml | indent 8 }}
      initContainers:
      - name: init-myservice
        image: busybox:1.31.1
        command: ['sh', '-c', "until wget -qO- $nrfUri &> /dev/null; do echo waiting for $nrfUri; sleep 2; done"]
        env:
        - name: nrfUri
          value: {{ .Values.configuration.nrfUri }}
      containers:
        - name: free5g-305-udm 
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["./udm"]
          args:
            - -udmcfg
            - ../config/udmcfg.conf
          resources:
{{ .Values.resources | toYaml | indent 12 }}
          securityContext:
            privileged: false
          volumeMounts:
            - name: f5gc-udm-config
              mountPath: /free5gc/config
            - name: f5gc-udm-cert
              mountPath: /free5gc/support/TLS
          ports:
            - containerPort: {{ .Values.service.port }}
              name: f5gc-udm
              protocol: TCP
{{- if .Values.tcpdump.image }}
        - name: tcpdump
          image: {{ .Values.tcpdump.image }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sleep
            - infinity
          resources:
            limits:
              cpu: 100m
              memory: 64Mi
{{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccountName: f5gc-udm-sa
      terminationGracePeriodSeconds: 30
      volumes:
        - name: f5gc-udm-cert
          secret:
            secretName: f5gc-udm-tls-secret
        - name: f5gc-udm-config
          configMap:
            name: f5gc-udm-config
