apiVersion: v1
kind: Service
metadata:
  name: free5g
spec:
  selector:
    baseApp: free5g
  clusterIP: None
  ports:
  - name: foo # Actually, no port is needed.
    port: 1234
    targetPort: 1234

